//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id empresa solo puede contener letras, numeros y el caracter guión bajo ( _ ).
        /// </summary>
        internal static string CompanyValidation_AlfanumericsDomain {
            get {
                return ResourceManager.GetString("CompanyValidation_AlfanumericsDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La moneda de la compañia es obligatoria.
        /// </summary>
        internal static string CompanyValidation_EmptyCurrency {
            get {
                return ResourceManager.GetString("CompanyValidation_EmptyCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id empresa es obligatorio.
        /// </summary>
        internal static string CompanyValidation_EmptyDomain {
            get {
                return ResourceManager.GetString("CompanyValidation_EmptyDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La razón social es obligatorio.
        /// </summary>
        internal static string CompanyValidation_EmptyName {
            get {
                return ResourceManager.GetString("CompanyValidation_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id empresa ya se encuentra en uso.
        /// </summary>
        internal static string CompanyValidation_ExistsDomain {
            get {
                return ResourceManager.GetString("CompanyValidation_ExistsDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El id empresa debe tener entre 3 y 50 caracteres.
        /// </summary>
        internal static string CompanyValidation_LengthDomain {
            get {
                return ResourceManager.GetString("CompanyValidation_LengthDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La razón social debe tener entre 2 y 20 caracteres..
        /// </summary>
        internal static string CompanyValidation_LengthName {
            get {
                return ResourceManager.GetString("CompanyValidation_LengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es obligatorio.
        /// </summary>
        internal static string CostCenterValidation_EmptyName {
            get {
                return ResourceManager.GetString("CostCenterValidation_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El centro de costos no existe.
        /// </summary>
        internal static string CostCenterValidation_ExistsId {
            get {
                return ResourceManager.GetString("CostCenterValidation_ExistsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre debe tener tener menos de 50 caracteres.
        /// </summary>
        internal static string CostCenterValidation_LengthName {
            get {
                return ResourceManager.GetString("CostCenterValidation_LengthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar.
        /// </summary>
        internal static string Dashboard_Index_ApproveModal_ButtonApprove {
            get {
                return ResourceManager.GetString("Dashboard_Index_ApproveModal_ButtonApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Dashboard_Index_ApproveModal_ButtonCancel {
            get {
                return ResourceManager.GetString("Dashboard_Index_ApproveModal_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto total a aprobar.
        /// </summary>
        internal static string Dashboard_Index_ApproveModal_LabelAmount {
            get {
                return ResourceManager.GetString("Dashboard_Index_ApproveModal_LabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea aprobar el siguiente importe?.
        /// </summary>
        internal static string Dashboard_Index_ApproveModal_Title {
            get {
                return ResourceManager.GetString("Dashboard_Index_ApproveModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar.
        /// </summary>
        internal static string Dashboard_Index_ButtonApprove {
            get {
                return ResourceManager.GetString("Dashboard_Index_ButtonApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagar.
        /// </summary>
        internal static string Dashboard_Index_ButtonPay {
            get {
                return ResourceManager.GetString("Dashboard_Index_ButtonPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        internal static string Dashboard_Index_ButtonReject {
            get {
                return ResourceManager.GetString("Dashboard_Index_ButtonReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar.
        /// </summary>
        internal static string Dashboard_Index_ButtonSearch {
            get {
                return ResourceManager.GetString("Dashboard_Index_ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarjetas.
        /// </summary>
        internal static string Dashboard_Index_ButtonViewCards {
            get {
                return ResourceManager.GetString("Dashboard_Index_ButtonViewCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabla.
        /// </summary>
        internal static string Dashboard_Index_ButtonViewTable {
            get {
                return ResourceManager.GetString("Dashboard_Index_ButtonViewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        internal static string Dashboard_Index_DownloadExcel {
            get {
                return ResourceManager.GetString("Dashboard_Index_DownloadExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        internal static string Dashboard_Index_InputDateFrom {
            get {
                return ResourceManager.GetString("Dashboard_Index_InputDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        internal static string Dashboard_Index_InputDateTo {
            get {
                return ResourceManager.GetString("Dashboard_Index_InputDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado.
        /// </summary>
        internal static string Dashboard_Index_InputEmployee {
            get {
                return ResourceManager.GetString("Dashboard_Index_InputEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Rendición.
        /// </summary>
        internal static string Dashboard_Index_InputExpenseReportId {
            get {
                return ResourceManager.GetString("Dashboard_Index_InputExpenseReportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Gasto.
        /// </summary>
        internal static string Dashboard_Index_InputExpenseType {
            get {
                return ResourceManager.GetString("Dashboard_Index_InputExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filas.
        /// </summary>
        internal static string Dashboard_Index_InputRecordCount {
            get {
                return ResourceManager.GetString("Dashboard_Index_InputRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobados.
        /// </summary>
        internal static string Dashboard_Index_LabelApprovedCount {
            get {
                return ResourceManager.GetString("Dashboard_Index_LabelApprovedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de Gastos Asociados:.
        /// </summary>
        internal static string Dashboard_Index_LabelAssociatedEMokonaCount {
            get {
                return ResourceManager.GetString("Dashboard_Index_LabelAssociatedEMokonaCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últimas Rendiciones.
        /// </summary>
        internal static string Dashboard_Index_LabelLastReports {
            get {
                return ResourceManager.GetString("Dashboard_Index_LabelLastReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendientes.
        /// </summary>
        internal static string Dashboard_Index_LabelPendingCount {
            get {
                return ResourceManager.GetString("Dashboard_Index_LabelPendingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazados.
        /// </summary>
        internal static string Dashboard_Index_LabelRejectedCount {
            get {
                return ResourceManager.GetString("Dashboard_Index_LabelRejectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seleccionados.
        /// </summary>
        internal static string Dashboard_Index_LabelSelectedEMokonaReports {
            get {
                return ResourceManager.GetString("Dashboard_Index_LabelSelectedEMokonaReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver detalle.
        /// </summary>
        internal static string Dashboard_Index_LinkViewEMokonaReportDetail {
            get {
                return ResourceManager.GetString("Dashboard_Index_LinkViewEMokonaReportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Dashboard_Index_PayModal_ButtonCancel {
            get {
                return ResourceManager.GetString("Dashboard_Index_PayModal_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagar.
        /// </summary>
        internal static string Dashboard_Index_PayModal_ButtonPay {
            get {
                return ResourceManager.GetString("Dashboard_Index_PayModal_ButtonPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto total a pagar.
        /// </summary>
        internal static string Dashboard_Index_PayModal_LabelAmount {
            get {
                return ResourceManager.GetString("Dashboard_Index_PayModal_LabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea pagar el siguiente importe?.
        /// </summary>
        internal static string Dashboard_Index_PayModal_Title {
            get {
                return ResourceManager.GetString("Dashboard_Index_PayModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Dashboard_Index_RejectModal_ButtonCancel {
            get {
                return ResourceManager.GetString("Dashboard_Index_RejectModal_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        internal static string Dashboard_Index_RejectModal_ButtonReject {
            get {
                return ResourceManager.GetString("Dashboard_Index_RejectModal_ButtonReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto total a rechazar.
        /// </summary>
        internal static string Dashboard_Index_RejectModal_LabelAmount {
            get {
                return ResourceManager.GetString("Dashboard_Index_RejectModal_LabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea rechazar el siguiente importe?.
        /// </summary>
        internal static string Dashboard_Index_RejectModal_Title {
            get {
                return ResourceManager.GetString("Dashboard_Index_RejectModal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        internal static string Dashboard_Index_TableHeaderAmount {
            get {
                return ResourceManager.GetString("Dashboard_Index_TableHeaderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Creación.
        /// </summary>
        internal static string Dashboard_Index_TableHeaderCreationDate {
            get {
                return ResourceManager.GetString("Dashboard_Index_TableHeaderCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        internal static string Dashboard_Index_TableHeaderDescription {
            get {
                return ResourceManager.GetString("Dashboard_Index_TableHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado.
        /// </summary>
        internal static string Dashboard_Index_TableHeaderEmployee {
            get {
                return ResourceManager.GetString("Dashboard_Index_TableHeaderEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° rendici&amp;oacute;n.
        /// </summary>
        internal static string Dashboard_Index_TableHeaderId {
            get {
                return ResourceManager.GetString("Dashboard_Index_TableHeaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string Dashboard_Index_TableHeaderTitle {
            get {
                return ResourceManager.GetString("Dashboard_Index_TableHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobado.
        /// </summary>
        internal static string EMokonaReport_Detail_LabelApproved {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_LabelApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente.
        /// </summary>
        internal static string EMokonaReport_Detail_LabelPending {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_LabelPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazado.
        /// </summary>
        internal static string EMokonaReport_Detail_LabelRejected {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_LabelRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Aprobado.
        /// </summary>
        internal static string EMokonaReport_Detail_LabelTotalApproved {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_LabelTotalApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Rechazado.
        /// </summary>
        internal static string EMokonaReport_Detail_LabelTotalRejected {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_LabelTotalRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar.
        /// </summary>
        internal static string EMokonaReport_Detail_Modal_ButtonApprove {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_Modal_ButtonApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string EMokonaReport_Detail_Modal_ButtonCancel {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_Modal_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        internal static string EMokonaReport_Detail_Modal_ButtonReject {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_Modal_ButtonReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto total a aprobar.
        /// </summary>
        internal static string EMokonaReport_Detail_Modal_LabelApproveAmount {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_Modal_LabelApproveAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto total a rechazar.
        /// </summary>
        internal static string EMokonaReport_Detail_Modal_LabelRejectAmount {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_Modal_LabelRejectAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea aprobar el siguiente importe?.
        /// </summary>
        internal static string EMokonaReport_Detail_Modal_ParagraphApprove {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_Modal_ParagraphApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea rechazar el siguiente gasto?.
        /// </summary>
        internal static string EMokonaReport_Detail_Modal_ParagraphReject {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_Modal_ParagraphReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        internal static string EMokonaReport_Detail_TableHeaderAmount {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_TableHeaderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costos.
        /// </summary>
        internal static string EMokonaReport_Detail_TableHeaderCostCenter {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_TableHeaderCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Creación.
        /// </summary>
        internal static string EMokonaReport_Detail_TableHeaderCreationDate {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_TableHeaderCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Doc..
        /// </summary>
        internal static string EMokonaReport_Detail_TableHeaderDocumentNumber {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_TableHeaderDocumentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Doc..
        /// </summary>
        internal static string EMokonaReport_Detail_TableHeaderDocumentType {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_TableHeaderDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Gasto.
        /// </summary>
        internal static string EMokonaReport_Detail_TableHeaderExpenseType {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_TableHeaderExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string EMokonaReport_Detail_TableHeaderStatus {
            get {
                return ResourceManager.GetString("EMokonaReport_Detail_TableHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string Expense_Detail_ButtonCancel {
            get {
                return ResourceManager.GetString("Expense_Detail_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Expense_Detail_ButtonSave {
            get {
                return ResourceManager.GetString("Expense_Detail_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        internal static string Expense_Detail_FieldAmount {
            get {
                return ResourceManager.GetString("Expense_Detail_FieldAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costos.
        /// </summary>
        internal static string Expense_Detail_FieldCostCenter {
            get {
                return ResourceManager.GetString("Expense_Detail_FieldCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        internal static string Expense_Detail_FieldDescription {
            get {
                return ResourceManager.GetString("Expense_Detail_FieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento.
        /// </summary>
        internal static string Expense_Detail_FieldDocumentType {
            get {
                return ResourceManager.GetString("Expense_Detail_FieldDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Expense_Detail_FieldExpenseDate {
            get {
                return ResourceManager.GetString("Expense_Detail_FieldExpenseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Gasto.
        /// </summary>
        internal static string Expense_Detail_FieldExpenseType {
            get {
                return ResourceManager.GetString("Expense_Detail_FieldExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado:.
        /// </summary>
        internal static string Expense_Detail_FieldStatus {
            get {
                return ResourceManager.GetString("Expense_Detail_FieldStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han adjuntado recibos o boletas a este gasto..
        /// </summary>
        internal static string Expense_Detail_ParagraphNoAttachments {
            get {
                return ResourceManager.GetString("Expense_Detail_ParagraphNoAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actual no tiene los permisos para realizar esta acción..
        /// </summary>
        internal static string Expense_UnauthorizedToApproveReject {
            get {
                return ResourceManager.GetString("Expense_UnauthorizedToApproveReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargar.
        /// </summary>
        internal static string GeneralReport_Filters_ButtonDownload {
            get {
                return ResourceManager.GetString("GeneralReport_Filters_ButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string GeneralReport_Filters_ButtonSearch {
            get {
                return ResourceManager.GetString("GeneralReport_Filters_ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costos.
        /// </summary>
        internal static string GeneralReport_Filters_FieldCostCenter {
            get {
                return ResourceManager.GetString("GeneralReport_Filters_FieldCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        internal static string GeneralReport_Filters_FieldDateFrom {
            get {
                return ResourceManager.GetString("GeneralReport_Filters_FieldDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        internal static string GeneralReport_Filters_FieldDateTo {
            get {
                return ResourceManager.GetString("GeneralReport_Filters_FieldDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento.
        /// </summary>
        internal static string GeneralReport_Filters_FieldDocumentType {
            get {
                return ResourceManager.GetString("GeneralReport_Filters_FieldDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Gasto.
        /// </summary>
        internal static string GeneralReport_Filters_FieldExpenseType {
            get {
                return ResourceManager.GetString("GeneralReport_Filters_FieldExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string GeneralReport_Filters_FieldStatus {
            get {
                return ResourceManager.GetString("GeneralReport_Filters_FieldStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado.
        /// </summary>
        internal static string GeneralReport_Filters_FieldUser {
            get {
                return ResourceManager.GetString("GeneralReport_Filters_FieldUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        internal static string GeneralReport_TableHeader_Amount {
            get {
                return ResourceManager.GetString("GeneralReport_TableHeader_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costos.
        /// </summary>
        internal static string GeneralReport_TableHeader_CostCenter {
            get {
                return ResourceManager.GetString("GeneralReport_TableHeader_CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string GeneralReport_TableHeader_Date {
            get {
                return ResourceManager.GetString("GeneralReport_TableHeader_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento.
        /// </summary>
        internal static string GeneralReport_TableHeader_DocumentType {
            get {
                return ResourceManager.GetString("GeneralReport_TableHeader_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Gasto.
        /// </summary>
        internal static string GeneralReport_TableHeader_ExpenseType {
            get {
                return ResourceManager.GetString("GeneralReport_TableHeader_ExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string GeneralReport_TableHeader_Status {
            get {
                return ResourceManager.GetString("GeneralReport_TableHeader_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitante.
        /// </summary>
        internal static string GeneralReport_TableHeader_User {
            get {
                return ResourceManager.GetString("GeneralReport_TableHeader_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReporteGeneral.
        /// </summary>
        internal static string GeneralReport_Title {
            get {
                return ResourceManager.GetString("GeneralReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016. Todos los derechos reservados.
        /// </summary>
        internal static string General_AllRightReserved {
            get {
                return ResourceManager.GetString("General_AllRightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollado por.
        /// </summary>
        internal static string General_DevelopBy {
            get {
                return ResourceManager.GetString("General_DevelopBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Hola {0}!.
        /// </summary>
        internal static string Layout_LabelGreetings {
            get {
                return ResourceManager.GetString("Layout_LabelGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis Rendiciones.
        /// </summary>
        internal static string Layout_LinkMyEMokona {
            get {
                return ResourceManager.GetString("Layout_LinkMyEMokona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte General.
        /// </summary>
        internal static string Layout_LinkReports {
            get {
                return ResourceManager.GetString("Layout_LinkReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string Layout_LinkSettings {
            get {
                return ResourceManager.GetString("Layout_LinkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        internal static string Layout_LinkSignIn {
            get {
                return ResourceManager.GetString("Layout_LinkSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cerrar sesión.
        /// </summary>
        internal static string Layout_LinkSignOut {
            get {
                return ResourceManager.GetString("Layout_LinkSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mokona.
        /// </summary>
        internal static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        internal static string Login_Index_ButtonSignIn {
            get {
                return ResourceManager.GetString("Login_Index_ButtonSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Empresa.
        /// </summary>
        internal static string Login_Index_FieldCompanyId {
            get {
                return ResourceManager.GetString("Login_Index_FieldCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string Login_Index_FieldPassword {
            get {
                return ResourceManager.GetString("Login_Index_FieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordar Usuario.
        /// </summary>
        internal static string Login_Index_FieldRememberMe {
            get {
                return ResourceManager.GetString("Login_Index_FieldRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese usuario.
        /// </summary>
        internal static string Login_Index_FieldUsername {
            get {
                return ResourceManager.GetString("Login_Index_FieldUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        internal static string Login_Index_LabelWelcome {
            get {
                return ResourceManager.GetString("Login_Index_LabelWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiero registrarme como.
        /// </summary>
        internal static string Login_Index_Label_IWantToSignIn {
            get {
                return ResourceManager.GetString("Login_Index_Label_IWantToSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string Login_Index_Label_IWantToSignInAsCompany {
            get {
                return ResourceManager.GetString("Login_Index_Label_IWantToSignInAsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string Login_Index_Label_IWantToSignInAsUser {
            get {
                return ResourceManager.GetString("Login_Index_Label_IWantToSignInAsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola, bienvenido a Mokona. El administrador de empresa aun no ha aprovado tu cuenta.
        ///&lt;br /&gt;
        ///Te haremos saber cuando todo este listo para que puedas empezar a usar Mokona..
        /// </summary>
        internal static string Login_PendingApproval_Paragraph {
            get {
                return ResourceManager.GetString("Login_PendingApproval_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendiente de Aprobación.
        /// </summary>
        internal static string Login_PendingApproval_Title {
            get {
                return ResourceManager.GetString("Login_PendingApproval_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola, bienvenido a Mokona. Antes de poder empezar a usar Mokona debes verificar tu cuenta de email.
        ///Te hemos enviado por un email con las instrucciones a seguir. Recuerda revisar tu carpeta de correo no deseado o spam en caso de no encontrarlo en tu buzón de entrada.
        ///&lt;br /&gt;&lt;br /&gt;
        ///Haznos saber si tienes algun problema durante el proceso..
        /// </summary>
        internal static string Login_VerifyEmail_Paragraph {
            get {
                return ResourceManager.GetString("Login_VerifyEmail_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica tu cuenta de Email.
        /// </summary>
        internal static string Login_VerifyEmail_Title {
            get {
                return ResourceManager.GetString("Login_VerifyEmail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Settings_Company_ButtonSave {
            get {
                return ResourceManager.GetString("Settings_Company_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando ....
        /// </summary>
        internal static string Settings_Company_ButtonSaving {
            get {
                return ResourceManager.GetString("Settings_Company_ButtonSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardado.
        /// </summary>
        internal static string Settings_Company_ButtonSuccess {
            get {
                return ResourceManager.GetString("Settings_Company_ButtonSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de la Compañía.
        /// </summary>
        internal static string Settings_Company_Title {
            get {
                return ResourceManager.GetString("Settings_Company_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Centro de Costos.
        /// </summary>
        internal static string Settings_CostCenter_Button_NewCostCenter {
            get {
                return ResourceManager.GetString("Settings_CostCenter_Button_NewCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Settings_CostCenter_PopupNew_ButtonCancel {
            get {
                return ResourceManager.GetString("Settings_CostCenter_PopupNew_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Settings_CostCenter_PopupNew_ButtonSave {
            get {
                return ResourceManager.GetString("Settings_CostCenter_PopupNew_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costos.
        /// </summary>
        internal static string Settings_CostCenter_PopupNew_LabelName {
            get {
                return ResourceManager.GetString("Settings_CostCenter_PopupNew_LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costos.
        /// </summary>
        internal static string Settings_CostCenter_PopupNew_Title {
            get {
                return ResourceManager.GetString("Settings_CostCenter_PopupNew_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        internal static string Settings_CostCenter_TableHeader_Actions {
            get {
                return ResourceManager.GetString("Settings_CostCenter_TableHeader_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costos.
        /// </summary>
        internal static string Settings_CostCenter_TableHeader_CostCenter {
            get {
                return ResourceManager.GetString("Settings_CostCenter_TableHeader_CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costos.
        /// </summary>
        internal static string Settings_CostCenter_Title {
            get {
                return ResourceManager.GetString("Settings_CostCenter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Tipo de Documento.
        /// </summary>
        internal static string Settings_DocumentTypes_ButtonNewDocumentType {
            get {
                return ResourceManager.GetString("Settings_DocumentTypes_ButtonNewDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Settings_DocumentTypes_PopUpNew_ButtonCancel {
            get {
                return ResourceManager.GetString("Settings_DocumentTypes_PopUpNew_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Settings_DocumentTypes_PopUpNew_ButtonSave {
            get {
                return ResourceManager.GetString("Settings_DocumentTypes_PopUpNew_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Settings_DocumentTypes_PopUpNew_FieldName {
            get {
                return ResourceManager.GetString("Settings_DocumentTypes_PopUpNew_FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento.
        /// </summary>
        internal static string Settings_DocumentTypes_PopUpNew_Title {
            get {
                return ResourceManager.GetString("Settings_DocumentTypes_PopUpNew_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aciones.
        /// </summary>
        internal static string Settings_DocumentTypes_TableHeaderActions {
            get {
                return ResourceManager.GetString("Settings_DocumentTypes_TableHeaderActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Documento.
        /// </summary>
        internal static string Settings_DocumentTypes_TableHeaderDocumentType {
            get {
                return ResourceManager.GetString("Settings_DocumentTypes_TableHeaderDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Documentos.
        /// </summary>
        internal static string Settings_DocumentType_Title {
            get {
                return ResourceManager.GetString("Settings_DocumentType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Settings_ExpenseType_ButtonCancel {
            get {
                return ResourceManager.GetString("Settings_ExpenseType_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Tipo de Gasto.
        /// </summary>
        internal static string Settings_ExpenseType_ButtonNewExpenseType {
            get {
                return ResourceManager.GetString("Settings_ExpenseType_ButtonNewExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Settings_ExpenseType_ButtonSave {
            get {
                return ResourceManager.GetString("Settings_ExpenseType_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costos.
        /// </summary>
        internal static string Settings_ExpenseType_LabelDefaultCostCenter {
            get {
                return ResourceManager.GetString("Settings_ExpenseType_LabelDefaultCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Gasto.
        /// </summary>
        internal static string Settings_ExpenseType_LabelExpenseType {
            get {
                return ResourceManager.GetString("Settings_ExpenseType_LabelExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Tipo de Gasto.
        /// </summary>
        internal static string Settings_ExpenseType_Popupnew_Title {
            get {
                return ResourceManager.GetString("Settings_ExpenseType_Popupnew_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Gasto.
        /// </summary>
        internal static string Settings_ExpenseType_TableHeader_ExpenseType {
            get {
                return ResourceManager.GetString("Settings_ExpenseType_TableHeader_ExpenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costos.
        /// </summary>
        internal static string Settings_ExpenseType_TableHeader_TableHeader_DefaultCostCenter {
            get {
                return ResourceManager.GetString("Settings_ExpenseType_TableHeader_TableHeader_DefaultCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        internal static string Settings_ExpenseType_TableHeader_TableHeader_TableHeader_Actions {
            get {
                return ResourceManager.GetString("Settings_ExpenseType_TableHeader_TableHeader_TableHeader_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Gasto.
        /// </summary>
        internal static string Settings_ExpenseType_Title {
            get {
                return ResourceManager.GetString("Settings_ExpenseType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañía.
        /// </summary>
        internal static string Settings_SideMenu_LinkCompany {
            get {
                return ResourceManager.GetString("Settings_SideMenu_LinkCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Documentos.
        /// </summary>
        internal static string Settings_SideMenu_LinkDocumentTypes {
            get {
                return ResourceManager.GetString("Settings_SideMenu_LinkDocumentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Gastos.
        /// </summary>
        internal static string Settings_SideMenu_LinkExpenseTypes {
            get {
                return ResourceManager.GetString("Settings_SideMenu_LinkExpenseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        internal static string Settings_SideMenu_LinkUsers {
            get {
                return ResourceManager.GetString("Settings_SideMenu_LinkUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centros de Costos.
        /// </summary>
        internal static string Settings_SideMenu_LlinkCostCenter {
            get {
                return ResourceManager.GetString("Settings_SideMenu_LlinkCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar Cuenta.
        /// </summary>
        internal static string Settings_Users_ApproveButton {
            get {
                return ResourceManager.GetString("Settings_Users_ApproveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string Settings_Users_EditButton {
            get {
                return ResourceManager.GetString("Settings_Users_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Settings_Users_NewPopup_ButtonCancel {
            get {
                return ResourceManager.GetString("Settings_Users_NewPopup_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Settings_Users_NewPopup_ButtonSave {
            get {
                return ResourceManager.GetString("Settings_Users_NewPopup_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Settings_Users_NewPopup_LabelEmail {
            get {
                return ResourceManager.GetString("Settings_Users_NewPopup_LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string Settings_Users_NewPopup_LabelLastName {
            get {
                return ResourceManager.GetString("Settings_Users_NewPopup_LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Settings_Users_NewPopup_LabelName {
            get {
                return ResourceManager.GetString("Settings_Users_NewPopup_LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string Settings_Users_NewPopup_LabelRole {
            get {
                return ResourceManager.GetString("Settings_Users_NewPopup_LabelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle del Usuario.
        /// </summary>
        internal static string Settings_Users_NewPopup_Title {
            get {
                return ResourceManager.GetString("Settings_Users_NewPopup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar Cuenta.
        /// </summary>
        internal static string Settings_Users_RejectButton {
            get {
                return ResourceManager.GetString("Settings_Users_RejectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acciones.
        /// </summary>
        internal static string Settings_Users_TableHeader_Actions {
            get {
                return ResourceManager.GetString("Settings_Users_TableHeader_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Settings_Users_TableHeader_Email {
            get {
                return ResourceManager.GetString("Settings_Users_TableHeader_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string Settings_Users_TableHeader_FullName {
            get {
                return ResourceManager.GetString("Settings_Users_TableHeader_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        internal static string Settings_Users_TableHeader_Role {
            get {
                return ResourceManager.GetString("Settings_Users_TableHeader_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        internal static string Settings_Users_Title {
            get {
                return ResourceManager.GetString("Settings_Users_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario solo puede contener letras, números y el caracter guión bajo ( _ ).
        /// </summary>
        internal static string SignUpValidation_AlfanumericsLoginName {
            get {
                return ResourceManager.GetString("SignUpValidation_AlfanumericsLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id de empresa es obligatorio.
        /// </summary>
        internal static string SignUpValidation_EmptyCompanyDomain {
            get {
                return ResourceManager.GetString("SignUpValidation_EmptyCompanyDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Email es obligatorio.
        /// </summary>
        internal static string SignUpValidation_EmptyEmail {
            get {
                return ResourceManager.GetString("SignUpValidation_EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El primer nombre es obligatorio.
        /// </summary>
        internal static string SignUpValidation_EmptyFirstName {
            get {
                return ResourceManager.GetString("SignUpValidation_EmptyFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido es obligatorio.
        /// </summary>
        internal static string SignUpValidation_EmptyLastName {
            get {
                return ResourceManager.GetString("SignUpValidation_EmptyLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario es obligatorio.
        /// </summary>
        internal static string SignUpValidation_EmptyLoginName {
            get {
                return ResourceManager.GetString("SignUpValidation_EmptyLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es obligatoria.
        /// </summary>
        internal static string SignUpValidation_EmptyPassword {
            get {
                return ResourceManager.GetString("SignUpValidation_EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id empresa no corresponde a ninguna empresa en el sistema.
        /// </summary>
        internal static string SignUpValidation_ExistingCompanyDomain {
            get {
                return ResourceManager.GetString("SignUpValidation_ExistingCompanyDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario ya se encuentra en uso por otro usuario de la empresa.
        /// </summary>
        internal static string SignUpValidation_ExistsLoginName {
            get {
                return ResourceManager.GetString("SignUpValidation_ExistsLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Email es inválido.
        /// </summary>
        internal static string SignUpValidation_InvalidEmail {
            get {
                return ResourceManager.GetString("SignUpValidation_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Id empresa debe tener entre 3 y 50 caracteres.
        /// </summary>
        internal static string SignUpValidation_LenghtCompanyDomain {
            get {
                return ResourceManager.GetString("SignUpValidation_LenghtCompanyDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El primer nombre debe tener entre 2 y 20 caracteres.
        /// </summary>
        internal static string SignUpValidation_LengthFirstName {
            get {
                return ResourceManager.GetString("SignUpValidation_LengthFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido debe tener entre 2 y 20 caracteres.
        /// </summary>
        internal static string SignUpValidation_LengthLastName {
            get {
                return ResourceManager.GetString("SignUpValidation_LengthLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario debe tener entre 3 y 20 caracteres.
        /// </summary>
        internal static string SignUpValidation_LengthLoginName {
            get {
                return ResourceManager.GetString("SignUpValidation_LengthLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe tener por lo menos 4 caracteres.
        /// </summary>
        internal static string SignUpValidation_LengthPassword {
            get {
                return ResourceManager.GetString("SignUpValidation_LengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        internal static string SignUpValidation_PasswordsMismatch {
            get {
                return ResourceManager.GetString("SignUpValidation_PasswordsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casi terminamos. Ahora tienes que verificar tu cuenta de correo. Ve a tu cuenta de correo y sigue las instrucciónes que te enviamos por email.
        ///&lt;br /&gt;
        ///Si el email no esta en tu buzón de entrada, recuerda revisar la carpeta de correo no deseado o spam..
        /// </summary>
        internal static string SignUp_CheckYourEmail_Paragraph {
            get {
                return ResourceManager.GetString("SignUp_CheckYourEmail_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisa tu correo.
        /// </summary>
        internal static string SignUp_CheckYourEmail_Title {
            get {
                return ResourceManager.GetString("SignUp_CheckYourEmail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razón Social.
        /// </summary>
        internal static string SignUp_Company_FieldCompanyName {
            get {
                return ResourceManager.GetString("SignUp_Company_FieldCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda de la compañía.
        /// </summary>
        internal static string SignUp_Company_FieldCurrency {
            get {
                return ResourceManager.GetString("SignUp_Company_FieldCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Administrador.
        /// </summary>
        internal static string SignUp_Company_TitleAdminUser {
            get {
                return ResourceManager.GetString("SignUp_Company_TitleAdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de la compañía.
        /// </summary>
        internal static string SignUp_Company_TitleCompanyInformation {
            get {
                return ResourceManager.GetString("SignUp_Company_TitleCompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso de registraci&amp;óacute;n se completo satisfactoriamente. Ya puedes iniciar sesi&amp;oacute;n usando la informaci&amp;oacute;n 
        ///            que nos fue brindada. Tambi&amp;eacute;n puedes usar esta misma informaci&amp;oacute;n para iniciar sesi&amp;oacute;n en la App movil. No olvides probarla.
        ///            &lt;br /&gt;
        ///            &lt;br /&gt;
        ///            Ahora, intenta ingresar para comenzar a usar Mokona:.
        /// </summary>
        internal static string SignUp_Success_Paragraph {
            get {
                return ResourceManager.GetString("SignUp_Success_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Bienvenido a Mokona!.
        /// </summary>
        internal static string SignUp_Success_Title {
            get {
                return ResourceManager.GetString("SignUp_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        internal static string SignUp_User_ButtonCreate {
            get {
                return ResourceManager.GetString("SignUp_User_ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Contraseña.
        /// </summary>
        internal static string SignUp_User_FieldConfirmPassword {
            get {
                return ResourceManager.GetString("SignUp_User_FieldConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SignUp_User_FieldEmail {
            get {
                return ResourceManager.GetString("SignUp_User_FieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id de Compañia.
        /// </summary>
        internal static string SignUp_User_FieldIDCompany {
            get {
                return ResourceManager.GetString("SignUp_User_FieldIDCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string SignUp_User_FieldLastName {
            get {
                return ResourceManager.GetString("SignUp_User_FieldLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer Nombre.
        /// </summary>
        internal static string SignUp_User_FieldName {
            get {
                return ResourceManager.GetString("SignUp_User_FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string SignUp_User_FieldPassword {
            get {
                return ResourceManager.GetString("SignUp_User_FieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario.
        /// </summary>
        internal static string SignUp_User_FieldUserName {
            get {
                return ResourceManager.GetString("SignUp_User_FieldUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registración.
        /// </summary>
        internal static string SignUp_User_Title {
            get {
                return ResourceManager.GetString("SignUp_User_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups!, algo salió mal durante la verifición. No pudimos verificar tu cuenta, por favor ponte en contacto con tu administrador para recibir ayuda..
        /// </summary>
        internal static string Verification_Fail_Paragraph {
            get {
                return ResourceManager.GetString("Verification_Fail_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallo la verificación.
        /// </summary>
        internal static string Verification_Fail_Title {
            get {
                return ResourceManager.GetString("Verification_Fail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemos verificado tu cuenta de email correctamente. Ahora solo queda esperar que el administrador de tu compañía apruebe tu usuario. Te enviaremos un correo cuando este todo listo..
        /// </summary>
        internal static string Verification_Success_Paragraph {
            get {
                return ResourceManager.GetString("Verification_Success_Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificación Exitosa.
        /// </summary>
        internal static string Verification_Success_Title {
            get {
                return ResourceManager.GetString("Verification_Success_Title", resourceCulture);
            }
        }
    }
}
